name: Node.js CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Fazer checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Etapa 2: Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Define a versão do Node.js usada

      # Etapa 3: Instalar dependências
      - name: Install Dependencies
        run: yarn install

      # Etapa 4: Rodar testes
      - name: Run Tests
        run: yarn test
